refactor: ARM-243 Removed marketing
Rocketmakers/armstrong-edge pull request #151
Opened 2023-03-10 14:26 UTC by norgru

## What's new?

Removed the marketing folder

## Ticket number(s) in JIRA (if internal)

ARM-243

[board](https://rocketmakers.atlassian.net/browse/ARM-243?atlOrigin=eyJpIjoiYjI3NjZhOTAxN2MwNDRhNGFmMDJhZmIyOWJmNjRmNDUiLCJwIjoiaiJ9)

## Checklist

- [ ] are your changes in Storybook?
- [ ] are any breaking changes documented in `docs/migrating_from_oldstrong.md`?
- [ ] does _everything_ have jsdoc?
- [ ] is everything exported from index.ts?
- [ ] are all new hooks added to `src/hooks/hooks.stories.mdx` or given their own docs in Storybook?
- [ ] are all new SCSS mixins added to `src/theme/mixins.stories.mdx`?
- [ ] are all new SCSS variables added to `src/theme/variables.stories.mdx`?

2023-03-10 15:43 UTC, clarehenningmarsh commented on module/.storybook/manager.ts
> -  brandImage: 'https://raw.githubusercontent.com/Rocketmakers/armstrong/master/marketing/src/assets/armstrong-logo.svg',
Did the SVG get moved so that it can be used in the README etc?

2023-03-10 15:45 UTC, jlews requested changes

2023-03-10 15:45 UTC, jlews commented on module-legacy/src/components/header/header.stories.tsx
> -      <Image src="https://raw.githubusercontent.com/Rocketmakers/armstrong/master/marketing/src/assets/armstrong-logo.svg" alt="armstrong logo" />
Same as above comment, we probably need to pull the logo in from somewhere else

2023-03-10 15:45 UTC, jlews commented on module/.storybook/manager.ts
> -  brandImage: 'https://raw.githubusercontent.com/Rocketmakers/armstrong/master/marketing/src/assets/armstrong-logo.svg',
and again

2023-03-10 16:03 UTC, norgru commented on module/.storybook/manager.ts
> -  brandImage: 'https://raw.githubusercontent.com/Rocketmakers/armstrong/master/marketing/src/assets/armstrong-logo.svg',
readded

2023-03-10 16:03 UTC, norgru commented on module/.storybook/manager.ts
> -  brandImage: 'https://raw.githubusercontent.com/Rocketmakers/armstrong/master/marketing/src/assets/armstrong-logo.svg',
Readded to module/src/assets:)

2023-03-13 13:56 UTC, jlews approved these changes

2023-03-13 14:08 UTC, merged